- name: Setup app
  hosts: app
  tags: app

  tasks:
    - name: Add secrets
      community.docker.docker_secret:
        name: "{{ item.name }}"
        data: "{{ lookup('env', item.env_var, default=undef()) }}"
      loop:
        - name: chr-app-secret-key-base
          env_var: PROD_APP_SECRET_KEY_BASE
        - name: chr-db-password
          env_var: PROD_DB_PASSWORD
        - name: chr-db-url
          env_var: PROD_DB_URL
        - name: email-ses-region
          env_var: EMAIL_SES_REGION
        - name: email-ses-access-key
          env_var: EMAIL_SES_ACCESS_KEY
        - name: email-ses-secret
          env_var: EMAIL_SES_SECRET
        - name: email-default-sender-address
          env_var: EMAIL_DEFAULT_SENDER_ADDRESS
        - name: email-default-sender-name
          env_var: EMAIL_DEFAULT_SENDER_NAME

    - name: Registry auth
      community.docker.docker_login:
        registry: "{{ lookup('env', 'PROD_REGISTRY_URL', default=undef()) }}"
        username: "{{ lookup('env', 'PROD_REGISTRY_USERNAME', default=undef()) }}"
        password: "{{ lookup('env', 'PROD_REGISTRY_PASSWORD', default=undef()) }}"
